'use client';

import { motion } from "framer-motion";
import { TrendingUp, ArrowLeft, Download, Send, Clock, AlertCircle, Phone } from "lucide-react";
import { Link } from "react-router-dom";

interface InterestInvoice {
  id: string;
  invoiceNumber: string;
  customerName: string;
  amount: number;
  daysOverdue: number;
  suggestedInterest: number;
  rateUsed: number;
}

export function InterestClient({ data }: { data: InterestInvoice[] }) {
  const totalPotential = data.reduce((acc, inv) => acc + inv.suggestedInterest, 0);

  const handleWhatsAppNotice = (inv: InterestInvoice) => {
    const text = `*Interest Recovery Notice - TextileGuard*\n\nDear ${inv.customerName},\n\nRegarding Invoice #${inv.invoiceNumber}, which is overdue by ${inv.daysOverdue} days. As per our credit policy, interest is accrued at ${inv.rateUsed}% p.a.\n\n*Accrued Interest:* ₹${inv.suggestedInterest.toLocaleString()}\n*Original Principal:* ₹${inv.amount.toLocaleString()}\n\nPlease clear the total outstanding immediately to avoid further accruals.\n\n_Auto-generated by TextileGuard Logic Engine_`;
    window.open(`https://wa.me/?text=${encodeURIComponent(text)}`, '_blank');
  };

  return (
    <div className="space-y-8 pb-20">
      {/* Header Stat Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        <motion.div 
          initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}
          className="glass p-6 rounded-[2rem] border border-border bg-ruby-500/5"
        >
          <div className="flex justify-between items-start mb-4">
            <div className="w-10 h-10 bg-ruby-500/20 rounded-xl flex items-center justify-center">
              <TrendingUp className="w-5 h-5 text-ruby-500" />
            </div>
          </div>
          <p className="text-xs text-muted-foreground font-bold uppercase tracking-widest mb-1">Total Interest At Risk</p>
          <h4 className="text-3xl font-black tracking-tighter text-ruby-500">₹{(totalPotential/1000).toFixed(1)}k</h4>
        </motion.div>

        <motion.div 
          initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }}
          className="glass p-6 rounded-[2rem] border border-border"
        >
          <div className="flex justify-between items-start mb-4">
            <div className="w-10 h-10 bg-indigo-500/20 rounded-xl flex items-center justify-center">
              <Clock className="w-5 h-5 text-indigo-500" />
            </div>
          </div>
          <p className="text-xs text-muted-foreground font-bold uppercase tracking-widest mb-1">Avg. Days Wait</p>
          <h4 className="text-3xl font-black tracking-tighter">48 Days</h4>
        </motion.div>
        
        <div className="lg:col-span-2 glass p-6 rounded-[2rem] border border-border bg-emerald-500/5 flex items-center justify-between">
          <div>
            <h3 className="font-bold text-emerald-500 flex items-center gap-2">
              <AlertCircle className="w-4 h-4" />
              Recovery Logic Active
            </h3>
            <p className="text-xs text-muted-foreground mt-1 max-w-xs">Interest is calculated @18% p.a. daily on balance due. Use suggest actions to recover financial loss.</p>
          </div>
          <button className="glass px-6 py-3 rounded-2xl border border-emerald-500/20 text-emerald-500 font-bold text-xs uppercase tracking-widest hover:bg-emerald-500/10 transition-all">
            Download Report
          </button>
        </div>
      </div>

      {/* Recovery List */}
      <div className="glass rounded-[2rem] border border-border overflow-hidden">
        <div className="p-8 border-b border-border flex justify-between items-center">
          <div>
            <h3 className="text-xl font-bold italic underline decoration-primary/30 underline-offset-8">Interest Recovery Ledger</h3>
            <p className="text-xs text-muted-foreground mt-2 font-medium tracking-tight">Accruals across all overdue invoices</p>
          </div>
          <div className="flex gap-2">
             <div className="glass px-4 py-2 rounded-xl text-[10px] font-black uppercase tracking-widest border border-primary/20 text-primary">
               Rate: 18% p.a.
             </div>
          </div>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="bg-secondary/30">
                <th className="text-left px-8 py-4 text-[10px] font-black text-muted-foreground uppercase tracking-widest">Details</th>
                <th className="text-right px-4 py-4 text-[10px] font-black text-muted-foreground uppercase tracking-widest">Principal</th>
                <th className="text-right px-4 py-4 text-[10px] font-black text-muted-foreground uppercase tracking-widest">Overdue</th>
                <th className="text-right px-4 py-4 text-[10px] font-black text-white uppercase tracking-widest bg-ruby-500/20">Accrued Interest</th>
                <th className="text-right px-8 py-4 text-[10px] font-black text-muted-foreground uppercase tracking-widest">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-border">
              {data.map((inv, i) => (
                <motion.tr 
                  key={inv.id} 
                  initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: i * 0.05 }}
                  className="hover:bg-secondary/40 transition-colors group"
                >
                  <td className="px-8 py-6">
                    <div className="font-bold text-foreground">#{inv.invoiceNumber}</div>
                    <div className="text-xs text-primary font-black uppercase tracking-tight mt-1">{inv.customerName}</div>
                  </td>
                  <td className="px-4 py-6 text-right font-semibold">₹{inv.amount.toLocaleString()}</td>
                  <td className="px-4 py-6 text-right">
                    <span className="text-xs font-black px-2 py-1 bg-amber-500/10 text-amber-500 rounded-lg">{inv.daysOverdue} Days</span>
                  </td>
                  <td className="px-4 py-6 text-right font-black text-ruby-500 bg-ruby-500/5 group-hover:bg-ruby-500/10 transition-colors">
                    ₹{inv.suggestedInterest.toLocaleString()}
                  </td>
                  <td className="px-8 py-6">
                    <div className="flex justify-end gap-2">
                       <button 
                         onClick={() => handleWhatsAppNotice(inv)}
                         className="p-2.5 glass border border-emerald-500/20 text-emerald-500 rounded-xl hover:bg-emerald-500 hover:text-white transition-all shadow-lg shadow-emerald-500/10"
                       >
                         <Phone className="w-4 h-4" />
                       </button>
                       <button className="px-4 py-2 bg-primary text-white rounded-xl font-bold text-[10px] uppercase tracking-widest hover:shadow-[0_10px_30px_rgba(var(--primary),0.3)] transition-all flex items-center gap-2">
                         <Download className="w-3.5 h-3.5" />
                         Debit Note
                       </button>
                    </div>
                  </td>
                </motion.tr>
              ))}
              {data.length === 0 && (
                <tr>
                  <td colSpan={5} className="py-20 text-center text-muted-foreground italic font-medium">
                    No overdue capital detected. Liquid recovery is optimal.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
